# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o main ./cmd/api/main.go"
  bin = "main"
  full_bin = "./main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true
