version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  worker:
    build: 
     context: .
     dockerfile: Dockerfile.worker
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/worker

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
